In [1]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("/kaggle/input/cafe-sales-dirty-data-for-cleaning-training/dirty_cafe_sales.csv")

In [3]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
df.shape

(10000, 8)

In [5]:
df=df.drop("Transaction ID",axis=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Item              9667 non-null   object
 1   Quantity          9862 non-null   object
 2   Price Per Unit    9821 non-null   object
 3   Total Spent       9827 non-null   object
 4   Payment Method    7421 non-null   object
 5   Location          6735 non-null   object
 6   Transaction Date  9841 non-null   object
dtypes: object(7)
memory usage: 547.0+ KB

In [7]:
#df=df.drop_duplicates()

In [8]:
df.shape

(10000, 7)

In [9]:
for var in df :
    print(df[var].value_counts())

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64
Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64
Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64
Transaction Date
UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-07-21     39
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [10]:
df.isnull().sum()

Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [11]:
for var in df:
    print(df[var].value_counts())

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64
Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64
Total Spent
6.0        979
12.0       939
3.0        930
4.0        923
20.0       746
15.0       734
8.0        677
10.0       524
2.0        497
9.0        479
5.0        468
16.0       444
25.0       259
7.5        237
1.0        232
4.5        225
1.5        205
UNKNOWN    165
ERROR      164
Name: count, dtype: int64
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64
Transaction Date
UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-07-21     39
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [12]:
for var in df:
    df[var] = df[var].replace(["UNKNOWN", "ERROR", "nan"], np.nan)
    df[var].fillna(df[var].mode()[0],inplace=True)

/tmp/ipykernel_13/3989406878.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[var].fillna(df[var].mode()[0],inplace=True)

In [13]:
df.isnull().sum()

Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [14]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [15]:
df["year"]=df['Transaction Date'].dt.year
df["year"]

0       2023
1       2023
2       2023
3       2023
4       2023
        ...
9995    2023
9996    2023
9997    2023
9998    2023
9999    2023
Name: year, Length: 10000, dtype: int32

In [16]:
df["month"]=df['Transaction Date'].dt.month
df["month"]

0        9
1        5
2        7
3        4
4        6
        ..
9995     8
9996     6
9997     3
9998    12
9999    11
Name: month, Length: 10000, dtype: int32

In [17]:
df["day"]=df['Transaction Date'].dt.day
df["day"]

0        8
1       16
2       19
3       27
4       11
        ..
9995    30
9996     2
9997     2
9998     2
9999     7
Name: day, Length: 10000, dtype: int32

In [18]:
df.drop('Transaction Date',axis=1,inplace=True)

In [19]:
df

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,year,month,day
0,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023,9,8
1,Cake,4,3.0,12.0,Cash,In-store,2023,5,16
2,Cookie,4,1.0,6.0,Credit Card,In-store,2023,7,19
3,Salad,2,5.0,10.0,Digital Wallet,Takeaway,2023,4,27
4,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023,6,11
...,...,...,...,...,...,...,...,...,...
9995,Coffee,2,2.0,4.0,Digital Wallet,Takeaway,2023,8,30
9996,Juice,3,3.0,3.0,Digital Wallet,Takeaway,2023,6,2
9997,Coffee,4,2.0,8.0,Digital Wallet,Takeaway,2023,3,2
9998,Cookie,3,3.0,3.0,Digital Wallet,Takeaway,2023,12,2
9999,Sandwich,3,4.0,12.0,Cash,In-store,2023,11,7

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Item            10000 non-null  object
 1   Quantity        10000 non-null  object
 2   Price Per Unit  10000 non-null  object
 3   Total Spent     10000 non-null  object
 4   Payment Method  10000 non-null  object
 5   Location        10000 non-null  object
 6   year            10000 non-null  int32
 7   month           10000 non-null  int32
 8   day             10000 non-null  int32
dtypes: int32(3), object(6)
memory usage: 586.1+ KB

In [21]:
numerical=["Quantity","Price Per Unit","Total Spent"]
for var in df[numerical]:
    #df[var]=df[var].str.replace(".","",regex=True)
    #if you want turn to int 
    df[var]=df[var].astype(float)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Item            10000 non-null  object
 1   Quantity        10000 non-null  float64
 2   Price Per Unit  10000 non-null  float64
 3   Total Spent     10000 non-null  float64
 4   Payment Method  10000 non-null  object
 5   Location        10000 non-null  object
 6   year            10000 non-null  int32
 7   month           10000 non-null  int32
 8   day             10000 non-null  int32
dtypes: float64(3), int32(3), object(3)
memory usage: 586.1+ KB

In [23]:
cat=[var for var in df.columns if df[var].dtype=="O"]
cat

['Item', 'Payment Method', 'Location']

In [24]:
le = LabelEncoder()
for var in df[cat]:
   df[var] = le.fit_transform(df[var])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Item            10000 non-null  int64
 1   Quantity        10000 non-null  float64
 2   Price Per Unit  10000 non-null  float64
 3   Total Spent     10000 non-null  float64
 4   Payment Method  10000 non-null  int64
 5   Location        10000 non-null  int64
 6   year            10000 non-null  int32
 7   month           10000 non-null  int32
 8   day             10000 non-null  int32
dtypes: float64(3), int32(3), int64(3)
memory usage: 586.1 KB

In [26]:
df.head()

,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,year,month,day
0,1,2.0,2.0,4.0,1,1,2023,9,8
1,0,4.0,3.0,12.0,0,0,2023,5,16
2,2,4.0,1.0,6.0,1,0,2023,7,19
3,4,2.0,5.0,10.0,2,1,2023,4,27
4,1,2.0,2.0,4.0,2,0,2023,6,11